### ISSUE TITLE
Error with missing headings value

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALLinter#2]
```
[Error](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground10linter%3Ainterview_wide_linter.yml#)

    [qsteenhuis@suffolk.edu](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground10linter%3Ainterview_wide_linter.yml#)

Error

[Retry](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground10linter%3Ainterview_wide_linter.yml#)

    TypeError: 'NoneType' object is not iterable

History
Tried to run mandatory code at 0.00000s

mandatory: True
code: |
  yaml_file
  results

Needed definition of results at 0.00003s
Tried to ask question at 0.00011s

event: results
question: |
  Interview Suggestions
subquestion: |
  ### Readability
  
  % for key, val in interview_scores.items():
  * ${ key } : ${ val }
  % endfor
  
  % if headings_warnings or warnings:
  ### Warnings:
  
  % for warning in headings_warnings:
  * ${ warning }
  % endfor
  
  % for warning in warnings:
  % if isinstance(warning, tuple):
  * ${ warning[0] } [Read more](${warning[1]})
  % else:
  * ${ warning }
  % endif
  % endfor
  
  % endif
help:
  label: |
    Text used
  content: |
    % for text in interview_texts:
  
    ${ text }
  
    ---
    <br>
    % endfor

Needed definition of headings_warnings at 0.00041s
Tried to run block at 0.00045s

code: |
  headings_warnings = headings_violations(headings)

Needed definition of headings at 0.00052s
Tried to run block at 0.00057s

code: |
  mako.runtime.UNDEFINED = DAEmpty()

  interview_texts_no_mako = [remove_mako(text) for text in interview_texts]
  headings = {key: remove_mako(text) for key, text in headings.items()}

Needed definition of headings at 0.57488s
Tried to run block at 0.57495s

code: |
  # identify all questions that set a variable in the interview
  interview_texts = get_all_text(yaml_parsed)
  headings = get_all_headings(yaml_parsed)

Tried to run block at 0.57572s

code: |
  headings_warnings = headings_violations(headings)

[Show variables and values](https://apps-dev.suffolklitlab.org/vars?i=docassemble.playground10linter%3Ainterview_wide_linter.yml)
Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7777, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 9110, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 2, in <module>
NameError: name 'results' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8539, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 4973, in ask
    subquestion = self.subcontent.text(user_dict).rstrip()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 1427, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/template.py", line 451, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 828, in _render
    _render_context(template, callable_, context, *args,
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7faa15dd84c0", line 43, in render_body
UnboundLocalError: local variable 'headings_warnings' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 6460, in index
    interview.assemble(user_dict, interview_status=interview_status)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8056, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7845, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8619, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8504, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 9110, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 1, in <module>
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/playground10linter/linter.py", line 82, in headings_violations
    heading_width = get_heading_width(heading)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/playground10linter/linter.py", line 64, in get_heading_width
    for char in heading_text:
TypeError: 'NoneType' object is not iterable
```

**Comment by BryceStevenWilley** [comment]
What's the file you uploaded? Never realized you were allowed to write displayed blocks without a `question` attribute, or with one directly set to `None`.
